---
alb_manange_haproxy: yes
alb_manange_openresty: yes
alb_manange_ufw: yes

alb_ufw_rules:
  - rule: allow
    port: 80
    proto: tcp
    comment: "HTTP port"
  - rule: allow
    port: 443
    proto: tcp
    comment: "HTTPS port"