---
# FILE:            group_vars/db_servers.yml
# LICENSE:         Public Domain

alb_manange_haproxy: no
alb_manange_openresty: no
alb_manange_ufw: yes

alb_ufw_rules:
  - rule: allow
    port: 3306
    proto: tcp
    comment: "MySQL port open for everyone"
