---
# FILE:            apps-server.yml
# LICENSE:         Public Domain


# ansible-playbook -i hosts apps-server.yml

- name: "apps_servers"
  hosts: apps_servers
  remote_user: root
  vars:
    # the variables from the following archives will be loaded by ansible
    # groups_vars/all.yml
    # groups_vars/db_servers.yml

  roles:
    - ap-application-load-balancer
